### ISSUE TITLE
Beacon.LiveAdmin.PageLive.mount/3 MatchError because session map is missing beacon_live_admin_page_url key

### ISSUE THREAD

**Issue by kgautreaux** [BeaconCMS/beacon_live_admin#70]
```
[error] #PID<0.1084.0> running Phoenix.Endpoint.SyncCodeReloadPlug (connection #PID<0.891.0>, stream id 29) terminated
Server: localhost:4001 (https)
Request: GET /admin/shell/pages
** (exit) an exception was raised:
    ** (MatchError) no match of right hand side value: %{"_csrf_token" => "02NPbENSTJ_tS9dtH-7XCTx7", "live_socket_id" => "users_sessions:OsOtaeAOGX4zWeTzFKvVL3auSZ_pi2vUYNK3hn6imhA=", "locale" => "en", "pages" => [{"/layouts", Beacon.LiveAdmin.LayoutEditorLive.Index, :index, %{}}, {"/layouts/new", Beacon.LiveAdmin.LayoutEditorLive.New, :new, %{}}, {"/layouts/:id", Beacon.LiveAdmin.LayoutEditorLive.Edit, :edit, %{}}, {"/layouts/:id/meta_tags", Beacon.LiveAdmin.LayoutEditorLive.MetaTags, :meta_tags, %{}}, {"/layouts/:id/revisions", Beacon.LiveAdmin.LayoutEditorLive.Revisions, :revisions, %{}}, {"/layouts/:id/resource_links", Beacon.LiveAdmin.LayoutEditorLive.ResourceLinks, :resource_links, %{}}, {"/pages", Beacon.LiveAdmin.PageEditorLive.Index, :index, %{}}, {"/pages/new", Beacon.LiveAdmin.PageEditorLive.New, :new, %{}}, {"/pages/:id", Beacon.LiveAdmin.PageEditorLive.Edit, :edit, %{}}, {"/pages/:id/meta_tags", Beacon.LiveAdmin.PageEditorLive.MetaTags, :meta_tags, %{}}, {"/pages/:id/schema", Beacon.LiveAdmin.PageEditorLive.Schema, :schema, %{}}, {"/pages/:id/revisions", Beacon.LiveAdmin.PageEditorLive.Revisions, :revisions, %{}}, {"/pages/:page_id/events", Beacon.LiveAdmin.PageEditorLive.EventHandlers, :events, %{}}, {"/pages/:page_id/events/:event_handler_id", Beacon.LiveAdmin.PageEditorLive.EventHandlers, :events, %{}}, {"/pages/:page_id/variants", Beacon.LiveAdmin.PageEditorLive.Variants, :variants, %{}}, {"/pages/:page_id/variants/:variant_id", Beacon.LiveAdmin.PageEditorLive.Variants, :variants, %{}}, {"/components", Beacon.LiveAdmin.ComponentEditorLive.Index, :index, %{}}, {"/components/new", Beacon.LiveAdmin.ComponentEditorLive.New, :new, %{}}, {"/components/:id", Beacon.LiveAdmin.ComponentEditorLive.Edit, :edit, %{}}, {"/media_library", Beacon.LiveAdmin.MediaLibraryLive.Index, :index, %{}}, {"/media_library/upload", Beacon.LiveAdmin.MediaLibraryLive.Index, :upload, %{}}, {"/media_library/:id", Beacon.LiveAdmin.MediaLibraryLive.Index, :show, %{}}], "user_token" => <<58, 195, 173, 105, 224, 14, 25, 126, 51, 89, 228, 243, 20, 171, 213, 47, 118, 174, 73, 159, 233, 139, 107, 212, 96, 210, 183, 134, 126, 162, 154, 16>>}
        (beacon_live_admin 0.1.0-dev) lib/beacon/live_admin/page_live.ex:29: Beacon.LiveAdmin.PageLive.mount/3
        (phoenix_live_view 0.19.5) lib/phoenix_live_view/utils.ex:394: anonymous fn/6 in Phoenix.LiveView.Utils.maybe_call_live_view_mount!/5
        (telemetry 1.2.1) /Users/kaygee/Sites/swell/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
        (phoenix_live_view 0.19.5) lib/phoenix_live_view/static.ex:278: Phoenix.LiveView.Static.call_mount_and_handle_params!/5
        (phoenix_live_view 0.19.5) lib/phoenix_live_view/static.ex:119: Phoenix.LiveView.Static.render/3
        (phoenix_live_view 0.19.5) lib/phoenix_live_view/controller.ex:39: Phoenix.LiveView.Controller.live_render/3
        (phoenix 1.7.7) lib/phoenix/router.ex:430: Phoenix.Router.__call__/5
        (swell 1.5.2) lib/swell_web/endpoint.ex:1: SwellWeb.Endpoint.plug_builder_call/2
        (swell 1.5.2) deps/plug/lib/plug/debugger.ex:136: SwellWeb.Endpoint."call (overridable 3)"/2
        (swell 1.5.2) lib/swell_web/endpoint.ex:1: SwellWeb.Endpoint.call/2
        (phoenix 1.7.7) lib/phoenix/endpoint/sync_code_reload_plug.ex:22: Phoenix.Endpoint.SyncCodeReloadPlug.do_call/4
        (plug_cowboy 2.6.1) lib/plug/cowboy/handler.ex:11: Plug.Cowboy.Handler.init/2
        (cowboy 2.10.0) /Users/kaygee/Sites/swell/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.10.0) /Users/kaygee/Sites/swell/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
        (cowboy 2.10.0) /Users/kaygee/Sites/swell/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
        (stdlib 5.0.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
```

I get this error even if I add the `on_mount` option to the router for `beacon_admin_site` and log in successfully.  This error also occurs on layouts, components, and media library.

I don't think this is a `node` connection issue because I can see the site on the root `admin` page but clicking on the button to navigate to the PageLive `live_view` blows up.

I did some inspection of the tuple returned from `Beacon.LiveAdmin.Router.__session_options__/3` and indeed there isn't a `"beacon_live_admin_page_url"` key in there.

I put a `dbg(session)` into the `Beacon.LiveAdmin.PageLive.mount/3` and got this:

```
[(beacon_live_admin 0.1.0-dev) deps/beacon_live_admin/lib/beacon/live_admin/page_live.ex:29: Beacon.LiveAdmin.PageLive.mount/3]
session #=> %{
  "_csrf_token" => "redacted",
  "live_socket_id" => "users_sessions:redacted",
  "locale" => "en",
  "pages" => [
    {"/layouts", Beacon.LiveAdmin.LayoutEditorLive.Index, :index, %{}},
    {"/layouts/new", Beacon.LiveAdmin.LayoutEditorLive.New, :new, %{}},
    {"/layouts/:id", Beacon.LiveAdmin.LayoutEditorLive.Edit, :edit, %{}},
    {"/layouts/:id/meta_tags", Beacon.LiveAdmin.LayoutEditorLive.MetaTags,
     :meta_tags, %{}},
    {"/layouts/:id/revisions", Beacon.LiveAdmin.LayoutEditorLive.Revisions,
     :revisions, %{}},
    {"/layouts/:id/resource_links",
     Beacon.LiveAdmin.LayoutEditorLive.ResourceLinks, :resource_links, %{}},
    {"/pages", Beacon.LiveAdmin.PageEditorLive.Index, :index, %{}},
    {"/pages/new", Beacon.LiveAdmin.PageEditorLive.New, :new, %{}},
    {"/pages/:id", Beacon.LiveAdmin.PageEditorLive.Edit, :edit, %{}},
    {"/pages/:id/meta_tags", Beacon.LiveAdmin.PageEditorLive.MetaTags,
     :meta_tags, %{}},
    {"/pages/:id/schema", Beacon.LiveAdmin.PageEditorLive.Schema, :schema, %{}},
    {"/pages/:id/revisions", Beacon.LiveAdmin.PageEditorLive.Revisions,
     :revisions, %{}},
    {"/pages/:page_id/events", Beacon.LiveAdmin.PageEditorLive.EventHandlers,
     :events, %{}},
    {"/pages/:page_id/events/:event_handler_id",
     Beacon.LiveAdmin.PageEditorLive.EventHandlers, :events, %{}},
    {"/pages/:page_id/variants", Beacon.LiveAdmin.PageEditorLive.Variants,
     :variants, %{}},
    {"/pages/:page_id/variants/:variant_id",
     Beacon.LiveAdmin.PageEditorLive.Variants, :variants, %{}},
    {"/components", Beacon.LiveAdmin.ComponentEditorLive.Index, :index, %{}},
    {"/components/new", Beacon.LiveAdmin.ComponentEditorLive.New, :new, %{}},
    {"/components/:id", Beacon.LiveAdmin.ComponentEditorLive.Edit, :edit, %{}},
    {"/media_library", Beacon.LiveAdmin.MediaLibraryLive.Index, :index, %{}},
    {"/media_library/upload", Beacon.LiveAdmin.MediaLibraryLive.Index, :upload,
     %{}},
    {"/media_library/:id", Beacon.LiveAdmin.MediaLibraryLive.Index, :show, %{}}
  ],
  "user_token" => <<redacted>>
}
```

I'm not sure why the session map  passed to `mount/3` in `PageLive` doesn't include the `"beacon_live_admin_page_url"`.

Can anyone provide any insight?

**Comment by leandrocp** [comment]
Hi @kgautreaux you need to add `Beacon.LiveAdmin.Plug` into the router pipeline. I'm working on the guides to make it more clear (https://github.com/BeaconCMS/beacon_live_admin/pull/69/files#diff-944de4be4097cc911ed52ae1bef463d98811941c992025b657e74b6e0fc9606cR39-R55) but either way it should raise if that key is not found here https://github.com/BeaconCMS/beacon_live_admin/blob/37679ae50c6257e8b0f5b3d6cc58cd69fb96ede9/lib/beacon/live_admin/page_live.ex#L29 so a PR is very welcome to raise with a friendly message asking to verify the router.

**Comment by kgautreaux** [comment]
Thank you very much.  I'll give that a try.  I see it now in `plug.ex`, I just never looked there yet. Appreciate the quick response.
